export interface Destination {
  id: string
  country: string
  city: string
  emoji: string
  lat: number
  lng: number
  image: string
  flightHours: number
  bestMonths: string
  avgPrice: string
  climate: 'warm' | 'gematigd' | 'koud'
  types: string[]
  budgets: string[]
  durations: string[]
  accommodation: string[]
  activities: string[]
}

export const DESTINATIONS: Destination[] = [
  {
    id: 'portugal',
    country: 'Portugal', city: 'Lissabon', emoji: '🇵🇹',
    lat: 38.7, lng: -9.1,
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&q=80',
    flightHours: 2.5, bestMonths: 'Apr – Okt', avgPrice: '€€',
    climate: 'warm',
    types: ['strand', 'cultuur', 'citytrip'],
    budgets: ['€€', '€€€'],
    durations: ['kort', 'middel'],
    accommodation: ['hotel', 'airbnb'],
    activities: ['wandelen', 'musea', 'uitgaan'],
  },
  {
    id: 'spain',
    country: 'Spanje', city: 'Barcelona', emoji: '🇪🇸',
    lat: 41.4, lng: 2.2,
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600&q=80',
    flightHours: 2, bestMonths: 'Mrt – Nov', avgPrice: '€€',
    climate: 'warm',
    types: ['strand', 'cultuur', 'citytrip'],
    budgets: ['€€', '€€€'],
    durations: ['kort', 'middel'],
    accommodation: ['hotel', 'airbnb'],
    activities: ['wandelen', 'musea', 'uitgaan'],
  },
  {
    id: 'italy',
    country: 'Italië', city: 'Rome', emoji: '🇮🇹',
    lat: 41.9, lng: 12.5,
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&q=80',
    flightHours: 2.5, bestMonths: 'Apr – Okt', avgPrice: '€€€',
    climate: 'gematigd',
    types: ['cultuur', 'citytrip'],
    budgets: ['€€', '€€€'],
    durations: ['kort', 'middel'],
    accommodation: ['hotel', 'airbnb'],
    activities: ['wandelen', 'musea'],
  },
  {
    id: 'greece',
    country: 'Griekenland', city: 'Santorini', emoji: '🇬🇷',
    lat: 36.4, lng: 25.4,
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600&q=80',
    flightHours: 3.5, bestMonths: 'Mei – Okt', avgPrice: '€€€',
    climate: 'warm',
    types: ['strand', 'cultuur'],
    budgets: ['€€€', '€€€€'],
    durations: ['kort', 'middel'],
    accommodation: ['resort', 'hotel'],
    activities: ['wandelen', 'musea', 'duiken'],
  },
  {
    id: 'thailand',
    country: 'Thailand', city: 'Koh Samui', emoji: '🇹🇭',
    lat: 9.5, lng: 100.1,
    image: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=600&q=80',
    flightHours: 11, bestMonths: 'Nov – Apr', avgPrice: '€€',
    climate: 'warm',
    types: ['strand', 'avontuur', 'cultuur'],
    budgets: ['€', '€€'],
    durations: ['middel', 'lang'],
    accommodation: ['resort', 'hotel', 'airbnb'],
    activities: ['duiken', 'wandelen', 'uitgaan'],
  },
  {
    id: 'bali',
    country: 'Indonesië', city: 'Bali', emoji: '🇮🇩',
    lat: -8.3, lng: 115.1,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80',
    flightHours: 14, bestMonths: 'Apr – Sep', avgPrice: '€€',
    climate: 'warm',
    types: ['strand', 'natuur', 'cultuur', 'avontuur'],
    budgets: ['€', '€€'],
    durations: ['middel', 'lang'],
    accommodation: ['resort', 'airbnb', 'hotel'],
    activities: ['duiken', 'wandelen', 'musea'],
  },
  {
    id: 'japan',
    country: 'Japan', city: 'Kyoto', emoji: '🇯🇵',
    lat: 35.0, lng: 135.7,
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80',
    flightHours: 12, bestMonths: 'Mrt – Mei, Sep – Nov', avgPrice: '€€€',
    climate: 'gematigd',
    types: ['cultuur', 'citytrip', 'avontuur'],
    budgets: ['€€€', '€€€€'],
    durations: ['middel', 'lang'],
    accommodation: ['hotel'],
    activities: ['wandelen', 'musea', 'uitgaan'],
  },
  {
    id: 'morocco',
    country: 'Marokko', city: 'Marrakech', emoji: '🇲🇦',
    lat: 31.6, lng: -8.0,
    image: 'https://images.unsplash.com/photo-1539020140153-e479b8d1f27a?w=600&q=80',
    flightHours: 3.5, bestMonths: 'Okt – Apr', avgPrice: '€',
    climate: 'warm',
    types: ['cultuur', 'avontuur'],
    budgets: ['€', '€€'],
    durations: ['kort', 'middel'],
    accommodation: ['hotel', 'airbnb'],
    activities: ['wandelen', 'musea', 'roadtrip'],
  },
  {
    id: 'croatia',
    country: 'Kroatië', city: 'Dubrovnik', emoji: '🇭🇷',
    lat: 42.6, lng: 18.1,
    image: 'https://images.unsplash.com/photo-1555990793-da11153b2473?w=600&q=80',
    flightHours: 2.5, bestMonths: 'Mei – Sep', avgPrice: '€€',
    climate: 'warm',
    types: ['strand', 'cultuur'],
    budgets: ['€€', '€€€'],
    durations: ['kort', 'middel'],
    accommodation: ['hotel', 'airbnb'],
    activities: ['wandelen', 'musea', 'duiken'],
  },
  {
    id: 'france',
    country: 'Frankrijk', city: 'Parijs', emoji: '🇫🇷',
    lat: 48.9, lng: 2.3,
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600&q=80',
    flightHours: 1.5, bestMonths: 'Mrt – Nov', avgPrice: '€€€',
    climate: 'gematigd',
    types: ['cultuur', 'citytrip'],
    budgets: ['€€€', '€€€€'],
    durations: ['kort', 'middel'],
    accommodation: ['hotel', 'airbnb'],
    activities: ['wandelen', 'musea', 'uitgaan'],
  },
  {
    id: 'turkey',
    country: 'Turkije', city: 'Istanbul', emoji: '🇹🇷',
    lat: 41.0, lng: 28.9,
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=600&q=80',
    flightHours: 3.5, bestMonths: 'Apr – Okt', avgPrice: '€€',
    climate: 'warm',
    types: ['cultuur', 'citytrip', 'strand'],
    budgets: ['€', '€€'],
    durations: ['kort', 'middel'],
    accommodation: ['hotel', 'resort'],
    activities: ['wandelen', 'musea', 'uitgaan'],
  },
  {
    id: 'maldives',
    country: 'Malediven', city: 'Malé', emoji: '🇲🇻',
    lat: 4.2, lng: 73.5,
    image: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600&q=80',
    flightHours: 10, bestMonths: 'Nov – Apr', avgPrice: '€€€€',
    climate: 'warm',
    types: ['strand'],
    budgets: ['€€€€'],
    durations: ['middel'],
    accommodation: ['resort'],
    activities: ['duiken'],
  },
  {
    id: 'iceland',
    country: 'IJsland', city: 'Reykjavik', emoji: '🇮🇸',
    lat: 64.1, lng: -21.9,
    image: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=600&q=80',
    flightHours: 3, bestMonths: 'Jun – Aug, Dec – Feb', avgPrice: '€€€',
    climate: 'koud',
    types: ['natuur', 'avontuur'],
    budgets: ['€€€', '€€€€'],
    durations: ['kort', 'middel'],
    accommodation: ['hotel', 'airbnb'],
    activities: ['wandelen', 'roadtrip'],
  },
  {
    id: 'norway',
    country: 'Noorwegen', city: 'Bergen', emoji: '🇳🇴',
    lat: 60.4, lng: 5.3,
    image: 'https://images.unsplash.com/photo-1527004013197-933b500c37c6?w=600&q=80',
    flightHours: 2.5, bestMonths: 'Jun – Sep', avgPrice: '€€€',
    climate: 'koud',
    types: ['natuur', 'avontuur'],
    budgets: ['€€€', '€€€€'],
    durations: ['middel'],
    accommodation: ['hotel', 'airbnb', 'camping'],
    activities: ['wandelen', 'roadtrip'],
  },
  {
    id: 'kenya',
    country: 'Kenia', city: 'Masai Mara', emoji: '🇰🇪',
    lat: -1.5, lng: 35.1,
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&q=80',
    flightHours: 8.5, bestMonths: 'Jul – Okt', avgPrice: '€€€',
    climate: 'warm',
    types: ['natuur', 'avontuur'],
    budgets: ['€€€', '€€€€'],
    durations: ['middel'],
    accommodation: ['hotel', 'camping'],
    activities: ['wandelen'],
  },
  {
    id: 'mexico',
    country: 'Mexico', city: 'Cancún', emoji: '🇲🇽',
    lat: 21.1, lng: -86.8,
    image: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=600&q=80',
    flightHours: 11, bestMonths: 'Dec – Apr', avgPrice: '€€',
    climate: 'warm',
    types: ['strand', 'cultuur', 'avontuur'],
    budgets: ['€€', '€€€'],
    durations: ['middel', 'lang'],
    accommodation: ['resort', 'hotel'],
    activities: ['duiken', 'wandelen', 'roadtrip'],
  },
  {
    id: 'dubai',
    country: 'Dubai', city: 'Dubai', emoji: '🇦🇪',
    lat: 25.2, lng: 55.3,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80',
    flightHours: 7, bestMonths: 'Okt – Apr', avgPrice: '€€€€',
    climate: 'warm',
    types: ['citytrip', 'strand'],
    budgets: ['€€€€'],
    durations: ['kort', 'middel'],
    accommodation: ['resort', 'hotel'],
    activities: ['musea', 'uitgaan'],
  },
  {
    id: 'srilanka',
    country: 'Sri Lanka', city: 'Colombo', emoji: '🇱🇰',
    lat: 7.9, lng: 80.8,
    image: 'https://images.unsplash.com/photo-1539635278303-d4002c07eae3?w=600&q=80',
    flightHours: 10.5, bestMonths: 'Dec – Mrt', avgPrice: '€€',
    climate: 'warm',
    types: ['strand', 'natuur', 'cultuur', 'avontuur'],
    budgets: ['€', '€€'],
    durations: ['middel', 'lang'],
    accommodation: ['hotel', 'airbnb'],
    activities: ['wandelen', 'duiken', 'roadtrip'],
  },
  {
    id: 'vietnam',
    country: 'Vietnam', city: 'Hội An', emoji: '🇻🇳',
    lat: 15.9, lng: 108.3,
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=600&q=80',
    flightHours: 11.5, bestMonths: 'Feb – Aug', avgPrice: '€',
    climate: 'warm',
    types: ['cultuur', 'avontuur', 'strand'],
    budgets: ['€', '€€'],
    durations: ['middel', 'lang'],
    accommodation: ['hotel', 'airbnb'],
    activities: ['wandelen', 'musea', 'roadtrip'],
  },
  {
    id: 'austria',
    country: 'Oostenrijk', city: 'Innsbruck', emoji: '🇦🇹',
    lat: 47.3, lng: 11.4,
    image: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=600&q=80',
    flightHours: 2, bestMonths: 'Dec – Mrt, Jun – Sep', avgPrice: '€€€',
    climate: 'koud',
    types: ['natuur', 'avontuur'],
    budgets: ['€€€', '€€€€'],
    durations: ['kort', 'middel'],
    accommodation: ['hotel', 'airbnb'],
    activities: ['skiën', 'wandelen'],
  },
]
